name: CI

on:
  schedule:
    - cron: "0 6 * * 3"
  workflow_dispatch:
    inputs:
      reset_sha:
        description: "Reset to sha"
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: build-linux-${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - aarch64-linux-android
        os:
          - ubuntu-latest
        bin:
          - geph4-client
        include:
          - target: aarch64-unknown-linux-musl
            use-cross: true
          - target: aarch64-linux-android
            use-cross: true
          # - target: i686-pc-windows-msvc
          #   os: windows-latest
          #   bin: geph4-client.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: geph-official/gephgui-wry
          fetch-depth: 0
          submodules: true
      - name: Reset latest tag
        run: git reset --hard $(git rev-list --all --max-count=1)
      - name: Reset to input ref
        if: inputs.reset_sha != null
        run: git reset --hard ${{ inputs.reset_sha }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install cross
        if: matrix.use-cross == true
        uses: taiki-e/install-action@cross
      # - name: Install musl-gcc
      #   if: |
      #     matrix.target == 'x86_64-unknown-linux-musl' ||
      #     matrix.target == 'aarch64-unknown-linux-musl'
      #   run: |
      #     sudo apt install musl-tools
      - name: install lib
        run: sudo apt install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev librsvg2-dev libssl-dev patchelf strace libpango1.0-dev libgdk-pixbuf2.0-dev gcc clang g++ zlib1g-dev libmpc-dev  libmpfr-dev libgmp-dev  build-essential
      - name: npm build
        working-directory: gephgui
        run: |
          npm install
          npm run build
      - name: Cargo build
        if: matrix.use-cross != true
        run: cargo build --target ${{ matrix.target }} --release --locked
      - name: Cross build
        if: matrix.use-cross == true
        run: cross build --target ${{ matrix.target }} --release --locked
      - name: Move
        run: |
          ls -lha target/${{ matrix.target }}/release
          mv target/${{ matrix.target }}/release/${{ matrix.bin }} ./
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.bin }}
      - name: Package
        run: 7z a ${{ matrix.bin }}-${{ matrix.target }}.7z ${{ matrix.bin }}
#       - name: Get tag
#         shell: bash
#         run: echo "tag=$(git describe --tags)" >> $GITHUB_ENV
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.MM.DD
      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
#           tag_name: ${{ env.tag }}
          tag_name: ${{ steps.current-time.outputs.formattedTime }}
          files: ${{ matrix.bin }}-${{ matrix.target }}.7z
