name: CI
on:
  push:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      reset_sha:
        description: "Reset to sha"
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  # CARGO_NET_GIT_FETCH_WITH_CLI: true
  # PKG_CONFIG_SYSROOT_DIR: /
permissions:
  contents: write

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    if: inputs.skip_sync != true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Sync
        env:
          upstream_repo: geph-official/gephgui-wry
        run: |
          git remote add upstream https://github.com/$upstream_repo.git
          git fetch upstream
          git reset --hard $(git log --all --pretty=format:'%H' -n 1)
          git push -f
          git push --tags -f
      - name: Check update
        run: |
          tag=$(git describe --tags)
          release_tag=$(gh api repos/touhoured/geph4-client-autobuild/releases/latest --jq '.tag_name')
          echo "tag=$tag" >> $GITHUB_ENV
          echo release_tag=$release_tag >> $GITHUB_ENV

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    needs: sync
    if: ${{ env.tag }} != ${{ env.release_tag }}
    strategy:
      matrix:
        target:
          # - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          # - aarch64-unknown-linux-musl
          # - aarch64-linux-android
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: geph-official/gephgui-wry
          fetch-depth: 0
      - name: Reset latest tag
        run: git reset --hard $(git rev-list --all --max-count=1)
      - name: Install cross
        uses: taiki-e/install-action@cross
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: build
        run: |
          cross build --target ${{ matrix.target }} --release
      - name: Package
        working-directory: target/${{ matrix.target }}/release
        run: |
          7z a gephgui-wry-${{ matrix.target }}.7z gephgui-wry
      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: target/${{ matrix.target }}/release/gephgui-wry-${{ matrix.target }}.7z
