name: Sync

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

env:
  upstream: geph-official/gephgui-wry

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Sync
        run: |
          git remote add upstream https://github.com/${upstream}.git
          git fetch upstream
          # git reset --hard $(git log --pretty=format:'%H' -n 1)
          git reset upstream/master
          git push -f
          git push --tags -f
